select
    cast(date as date) as activity_date,
    cast(channel as varchar) as channel,
    cast(source as varchar) as source,
    cast(medium as varchar) as medium,
    cast(campaign as varchar) as campaign,
    lower(cast(device as varchar)) as device,
    cast(city as varchar) as city,
    lower(cast(payment_method as varchar)) as payment_method,
    lower(cast(customer_type as varchar)) as customer_type,
    cast(sessions as bigint) as sessions,
    cast(users as bigint) as users,
    cast(product_views as bigint) as product_views,
    cast(add_to_carts as bigint) as add_to_carts,
    cast(begin_checkouts as bigint) as begin_checkouts,
    cast(purchases as bigint) as purchases,
    cast(units_sold as bigint) as units_sold,
    cast(gross_revenue_sar as decimal(18, 2)) as gross_revenue_sar,
    cast(discount_sar as decimal(18, 2)) as discount_sar,
    cast(refund_sar as decimal(18, 2)) as refund_sar,
    cast(net_revenue_sar as decimal(18, 2)) as net_revenue_sar,
    cast(cost_sar as decimal(18, 2)) as cost_sar,
    cast(ad_spend_sar as decimal(18, 2)) as ad_spend_sar
from {{ ref('commerce_daily') }}
