select
    cast(order_id as varchar) as order_id,
    cast(tracking_transaction_id as varchar) as tracking_transaction_id,
    cast(order_date as date) as order_date,
    cast(anonymous_customer_id as varchar) as anonymous_customer_id,
    lower(cast(customer_type as varchar)) as customer_type,
    cast(channel as varchar) as channel,
    cast(source as varchar) as source,
    cast(medium as varchar) as medium,
    cast(campaign as varchar) as campaign,
    lower(cast(device as varchar)) as device,
    cast(city as varchar) as city,
    lower(cast(payment_method as varchar)) as payment_method,
    cast(coupon_group as varchar) as coupon_group,
    lower(cast(order_status as varchar)) as order_status,
    cast(gross_revenue_sar as decimal(18, 2)) as gross_revenue_sar,
    cast(discount_sar as decimal(18, 2)) as discount_sar,
    cast(refund_sar as decimal(18, 2)) as refund_sar,
    cast(net_revenue_sar as decimal(18, 2)) as net_revenue_sar
from {{ ref('orders') }}
